### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by HarshitUSB** [DarrylSSY/Blockstackers-Towny#2]
I upgraded to rank 3 and it shows that now rank 2 us locked with red wool

**Comment by DarrylSSY** [comment]
> I upgraded to rank 3 and it shows that now rank 2 us locked with red wool

Please provide your IGN and screenshot of the ranks menu thanks ! :)

**Comment by HarshitUSB** [comment]
IGN - UnSayable_Beast
![1](https://user-images.githubusercontent.com/92025106/136664934-af790ce0-17ac-4622-b618-271ec4ab2ba2.png)
![2](https://user-images.githubusercontent.com/92025106/136664938-7e67089e-b38e-474b-a68c-cabd216412c6.png)

**Comment by DarrylSSY** [comment]
Fixed
