### ISSUE TITLE
(Bug) Incomplete Progress Bar 

### ISSUE THREAD

**Issue by Sivadithiyan** [DarrylSSY/Blockstackers-Towny#4]
As far my observation goes, the progress bar for the MCMMO mining skill is not properly displayed. The progress is not represented but the progress bar outlay/border alone appears when the player mines something. Most of the progress bar for other skills are perfectly fine.

https://user-images.githubusercontent.com/80585108/136380792-04b6f947-294b-4cba-a548-d85fe1a00798.png

**Comment by Sivadithiyan** [comment]
Update: Also for Alchemy Skill

**Comment by DarrylSSY** [comment]
Fixed, effective after a server restart, report again if the problem still persists.
