### ISSUE TITLE
(Bug) Taking damage in spawn area

### ISSUE THREAD

**Issue by Sivadithiyan** [DarrylSSY/Blockstackers-Towny#5]
Players can take damage and die in the spawn area (players can access their death chests). Fall damage and cactus pricking damage were observed. Players also lose saturation while walking/sprinting around the spawn area 

https://user-images.githubusercontent.com/80585108/136381402-060778be-c6c9-4d44-8e30-f725d63aaa54.png

**Comment by DarrylSSY** [comment]
Fixed, added healing
