### ISSUE TITLE
(Bug) Old /pwarp data persists

### ISSUE THREAD

**Issue by Sivadithiyan** [DarrylSSY/Blockstackers-Towny#6]
Players can teleport using the /pwarp <location_name> to teleport to player warps. The Data of player warps from previous season  still exists in the server so players can teleport to coordinates of old player warps(safe/unsafe). Cases like players entering end dimension without filling the portal by simply typing /pwarp EndFarm or constantly dying due to fall damage while using /pwarp (ended up losing inventory items after many unsuccessful attempts) has taken place before.

**Comment by DarrylSSY** [comment]
Fixed
